import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import CategoryCard from "../../../components/CategoryCard";
import Navbar from "../../../components/Navbar";
import { trpc } from "../../utils/trpc";

const Home: NextPage = () => {
  const session = useSession({ required: true });
  const categories = trpc.useQuery(["app.getCategories"]);

  return (
    <>
      <Head>
        <title>Bugtracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main>
        <h1 className="dark:text-white text-3xl text-center uppercase">
          Categories
        </h1>
        <div className="w-9/12 mx-auto">
          {categories.data && (
            <ul>
              {categories.data.map((category) => (
                <li key={category.id}>
                  <CategoryCard category={category} />
                </li>
              ))}
            </ul>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
