import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEvent } from "react";
import Navbar from "../../../components/Navbar";
import { trpc } from "../../utils/trpc";

const New: NextPage = () => {
  const mutation = trpc.useMutation(["app.createProject"]);
  const router = useRouter();

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const target = e.target as typeof e.target & {
      name: { value: string };
    };
    mutation.mutate({
      name: target.name.value,
    });
  };

  if (mutation.isSuccess) {
    router.push("/projects");
  }

  return (
    <>
      <Head>
        <title>Bugtracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main>
        <h1 className="text-center text-2xl uppercase dark:text-white">
          New Project
        </h1>
        <div className="w-[80%] mx-auto">
          <form onSubmit={handleSubmit}>
            <div className="flex flex-col">
              <label
                className="block text-gray-600 text-sm font-bold mb-2"
                htmlFor="name"
              >
                Name
              </label>
              <input
                className="shadow bg-gray-500 appearance-none border-none rounded w-full py-2 px-3 text-gray-300 leading-tight focus:shadow-outline"
                id="name"
                type="text"
                placeholder="Name"
              />
            </div>
            <button type="submit" className="btn w-full mt-8">
              Submit
            </button>
            {mutation.error && (
              <p className="mt-4 text-error">
                Something went wrong! Please check the form and try again!
              </p>
            )}
          </form>
        </div>
      </main>
    </>
  );
};

export default New;
